title: Ubuntu Fest
email: korea.ubuntu@gmail.com
description: 우분투와 딥러닝
baseurl: ""
url: "https://fest.ubuntu-kr.org"
registration-url: "https://festa.io/events/94"
github_username: ubuntu-fest

copyright: MIT License
owner: ubuntu-daejeon

# Location & time
period: "2018년 11월 10일"
period-time: "PM 1:00 ~ PM 6:00"
location: "충남대학교 공대 1호관 취봉홀"
address: "대전광역시 유성구 궁동 대학로 99"
location_query: "충남대학교"

# Event Sponsors
sponsors:
  - name: 캐노니컬
    image: CANONICAL.jpg
    url: https://www.canonical.com
    desc: >
      The company behind Ubuntu

supporters:
  - name: 충남대학교 SW중심대학
    image: CNU.jpg
    url: https://wise.cs-cnu.org/
    desc: >
      스마트 미래사회를 위한 창의적인 능력을 갖춘 글로벌 SW전문가 양성

host-a:
  - name: Kaggle Korea
    image: KAGGLE.jpg
    url: https://www.facebook.com/groups/230717130993727/
    desc: >
      함께 공부해서, 함께 나눕시다

host-b:
  - name: Keras Korea
    image: KERAS.png
    url: https://www.facebook.com/groups/KerasKorea/
    desc: >
      케라스, 그 간결함에 빠지다

host-c:
  - name: 우분투 한국 커뮤니티
    image: UBUNTU.png
    url: https://www.ubuntu-kr.org
    desc: >
      우분투를 사용하는 사람들의 모임

# Custom Collection
collections:
  sessions:
    title: Sessions
    output: true
    permalink: "/session/:path"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
