title: Ubuntu Fest
email: korea.ubuntu@gmail.com
description: Ubuntu Fest
baseurl: ""
url: "https://ubuntu-fest.github.io"

github_username: ubuntu-fest

copyright: MIT License
owner: ubuntu-daejeon

# Location & time
period: "2018년 11월 10일"
period-time: "오후 13:00 ~ 오후 18:00"
location: "장소: 충남대학교"
address: "대전광역시 유성구 궁동 대학로 99"
location_query: "충남대학교"

# Event Sponsors
sponsors:
  - name: 캐노니컬(example)
    image: CANONICAL.jpg
    url: https://www.canonical.com
    desc: >
      The company behind Ubuntu

supporters:
  - name: 충남대학교 SW중심대학
    image: CNU.jpg
    url: https://www.facebook.com/cnuwise/
    desc: >
      충남대학교 공과대학 SW중심대학 사업단

host-a:
  - name: Kaggle Korea
    image: KAGGLE.jpg
    url: https://www.facebook.com/groups/230717130993727/
    desc: >
      함께 공부해서, 함께 나눕시다

host-b:
  - name: Keras Korea
    image: KERAS.png
    url: https://www.facebook.com/groups/KerasKorea/
    desc: >
      케라스, 그 간결함에 빠지다

host-c:
  - name: ubuntu
    image: UBUNTU.png
    url: https://www.ubuntu-kr.org
    desc: >
      우분투 한국 커뮤니티

# Custom Collection
collections:
  sessions:
    title: Sessions
    output: true
    permalink: "/session/:path"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
